# based on: https://github.com/andry81/github-accum-stats
#

name: GitHub views counter for 14 days at every 8 hours and views accumulator

on:
  schedule:
    - cron: "0 */8 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  accum-gh-view-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: {{REPO_OWNER}}/gh-action--accum-gh-stats@master
        with:
          stat_repo_owner:          {{REPO_OWNER}}
          stat_repo:                myrepo
          stat_entity_path:         traffic/views
          stat_repo_read_token:     ${{ secrets.READ_STATS_TOKEN }}
          stats_list_key:           views

          curl_flags: >-
            -H 'Cache-Control: no-cache'

          output_repo_owner:        {{REPO_OWNER}}
          output_repo:              myrepo--gh-stats
          output_repo_branch:       master
          output_repo_dir:          traffic/views
          # NOTE: Can be `secrets.READ_STATS_TOKEN` as long as the input and the output repository does belong to the same owner.
          output_repo_write_token:  ${{ secrets.WRITE_STATS_TOKEN }}
